{{- if not .Values.useSGXDevPlugin }}
{{- required "A valid '.Values.useSGXDevPlugin' is required: \"enabled\"|\"scone\"|\"azure\"|\"disabled\"" .value }}
{{- else if and (ne .Values.useSGXDevPlugin "enabled") (ne .Values.useSGXDevPlugin "scone") (ne .Values.useSGXDevPlugin "azure") (ne .Values.useSGXDevPlugin "disabled") }}
{{- required "A valid '.Values.useSGXDevPlugin' is required: \"enabled\"|\"scone\"|\"azure\"|\"disabled\"" .value }}
{{- end }}

{{- if and (eq .Values.useSGXDevPlugin "azure") (not .Values.sgxEpcMem) }}
{{- required "Specify '.Values.sgxEpcMem' when using Azure SGX Device Plugin" .value }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "redis-cart.fullname" . }}
  labels:
    {{- include "redis-cart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "redis-cart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "redis-cart.selectorLabels" . | nindent 8 }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      volumes: 
        {{- if eq .Values.useSGXDevPlugin "disabled" }}
        - hostPath:
            path: /dev/isgx
          name: dev-isgx
        {{- end }}
      containers:
        - name: sconeapp
          {{- if .Values.command }}
          command: {{ .Values.command }}
          {{- end }}
          securityContext:
          {{- if or (eq .Values.useSGXDevPlugin "scone") (eq .Values.useSGXDevPlugin "enabled")}}
            capabilities:
              add: ["SYS_RAWIO"]
          {{- else if (eq .Values.useSGXDevPlugin "disabled") }}
            privileged: true
          {{- end}}
          image: "{{ .Values.image }}"
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
            - containerPort: 6379
          env:
            {{- if .Values.extraEnvVars }}
            {{- toYaml .Values.extraEnvVars | nindent 12 }}
            {{- end }}
            {{- if .Values.scone.configID }}
            - name: SCONE_CONFIG_ID
              value: {{ .Values.scone.configID }}
              {{- if .Values.scone.cas }}
            - name: SCONE_CAS_ADDR
              value: {{ .Values.scone.cas }}
              {{- end }}
              {{- if .Values.scone.las }}
            - name: SCONE_LAS_ADDR
              value: {{ .Values.scone.las }}
              {{- else }}
            - name: SCONE_LAS_ADDR
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
              {{- end }}
            {{- end }}
            {{- if .Values.scone.allowDlOpen }}
            - name: SCONE_ALLOW_DLOPEN
              value: {{ .Values.scone.allowDlOpen | quote }}
            {{- end }}
            {{- if .Values.scone.heap }}
            - name: SCONE_HEAP
              value: {{ .Values.scone.heap }}
            {{- end }}
            {{- if .Values.scone.stack }}
            - name: SCONE_STACK
              value: {{ .Values.scone.stack }}
            {{- end }}
            {{- if .Values.scone.fork }}
            - name: SCONE_FORK
              value: {{ .Values.scone.fork | quote }}
            {{- end }}
            {{- if .Values.scone.log }}
            - name: SCONE_LOG
              value: {{ .Values.scone.log | quote }}
            {{- end }}
            {{- if .Values.scone.printVersion }}
            - name: SCONE_VERSION
              value: "1"
            {{- end }}
          {{- if or (.Values.resources) (or (or (eq .Values.useSGXDevPlugin "scone") (eq .Values.useSGXDevPlugin "enabled")) (eq .Values.useSGXDevPlugin "azure")) }}
          resources:
            requests:
            {{- if .Values.resources.requests }}
              {{- toYaml .Values.resources.requests | nindent 14 }}
            {{- end }}
            limits:
            {{- if .Values.resources.limits }}
              {{- toYaml .Values.resources.limits | nindent 14 }}
            {{- end }}
              {{- if or (eq .Values.useSGXDevPlugin "scone") (eq .Values.useSGXDevPlugin "enabled") }}
              sgx.k8s.io/sgx: 1
              {{- else if eq .Values.useSGXDevPlugin "azure" }}
              kubernetes.azure.com/sgx_epc_mem_in_MiB: {{ .Values.sgxEpcMem }}
              {{- end }}
          {{- end }}
          volumeMounts: 
            {{- if eq .Values.useSGXDevPlugin "disabled" }}
            - name: dev-isgx
              mountPath: /dev/isgx
            {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
