{{- if .Values.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cart.fullname" . }}
  labels:
    {{- include "redis-cart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") (not (empty .Values.service.loadBalancerIP)) }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: 6379
      name: port-6379
  selector:
    {{- include "redis-cart.selectorLabels" . | nindent 4 }}
{{- end }}
